=== CNSLabs/agreements-data-standard/schemas/provable-inputs/transaction-proof.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Transaction Proof Schema",
  "description": "Schema for blockchain transaction proofs including raw transaction, receipt, block header, and merkle proofs",
  "type": "object",
  "required": ["txHash", "proofDefinitionReference", "rawTx", "txReceipt", "blockHeader", "receiptProof", "transactionProof"],
  "properties": {
    "txHash": {
      "type": "string",
      "description": "Hash of the transaction",
      "pattern": "^0x[a-fA-F0-9]{64}$"
    },
    "proofDefinitionReference": {
      "type": "string",
      "description": "Reference to the proof definition being used"
    },
    "rawTx": {
      "type": "object",
      "required": ["hash", "nonce", "from", "to", "value", "gasPrice", "gas", "input", "v", "r", "s", "chainId"],
      "properties": {
        "hash": {
          "type": "string",
          "pattern": "^0x[a-fA-F0-9]{64}$"
        },
        "nonce": {
          "type": "integer",
          "minimum": 0
        },
        "from": {
          "type": "string",
          "pattern": "^0x[a-fA-F0-9]{40}$"
        },
        "to": {
          "type": "string",
          "pattern": "^0x[a-fA-F0-9]{40}$"
        },
        "value": {
          "type": "string",
          "pattern": "^0x[a-fA-F0-9]*$"
        },
        "gasPrice": {
          "type": "string",
          "pattern": "^0x[a-fA-F0-9]*$"
        },
        "gas": {
          "type": "string",
          "pattern": "^0x[a-fA-F0-9]*$"
        },
        "input": {
          "type": "string",
          "pattern": "^0x[a-fA-F0-9]*$"
        },
        "v": {
          "type": "string",
          "pattern": "^0x[a-fA-F0-9]*$"
        },
        "r": {
          "type": "string",
          "pattern": "^0x[a-fA-F0-9]*$"
        },
        "s": {
          "type": "string",
          "pattern": "^0x[a-fA-F0-9]*$"
        },
        "chainId": {
          "type": "integer",
          "minimum": 1
        }
      }
    },
    "txReceipt": {
      "type": "object",
      "required": [
        "transactionHash",
        "transactionIndex",
        "type",
        "blockHash",
        "blockNumber",
        "from",
        "to",
        "gasUsed",
        "cumulativeGasUsed",
        "effectiveGasPrice",
        "contractAddress",
        "logs",
        "status",
        "logsBloom"
      ],
      "properties": {
        "transactionHash": {
          "type": "string",
          "pattern": "^0x[a-fA-F0-9]{64}$"
        },
        "transactionIndex": {
          "type": "integer",
          "minimum": 0
        },
        "type": {
          "type": "integer",
          "minimum": 0
        },
        "blockHash": {
          "type": "string",
          "pattern": "^0x[a-fA-F0-9]{64}$"
        },
        "blockNumber": {
          "type": "integer",
          "minimum": 0
        },
        "from": {
          "type": "string",
          "pattern": "^0x[a-fA-F0-9]{40}$"
        },
        "to": {
          "type": "string",
          "pattern": "^0x[a-fA-F0-9]{40}$"
        },
        "gasUsed": {
          "type": "integer",
          "minimum": 0
        },
        "cumulativeGasUsed": {
          "type": "integer",
          "minimum": 0
        },
        "effectiveGasPrice": {
          "type": "integer",
          "minimum": 0
        },
        "contractAddress": {
          "type": ["string", "null"],
          "pattern": "^0x[a-fA-F0-9]{40}$"
        },
        "logs": {
          "type": "array",
          "items": {
            "type": "object",
            "required": [
              "address",
              "topics",
              "data",
              "blockNumber",
              "transactionHash",
              "logIndex",
              "removed"
            ],
            "properties": {
              "address": {
                "type": "string",
                "pattern": "^0x[a-fA-F0-9]{40}$"
              },
              "topics": {
                "type": "array",
                "items": {
                  "type": "string",
                  "pattern": "^0x[a-fA-F0-9]{64}$"
                }
              },
              "data": {
                "type": "string",
                "pattern": "^0x[a-fA-F0-9]*$"
              },
              "blockNumber": {
                "type": "integer",
                "minimum": 0
              },
              "transactionHash": {
                "type": "string",
                "pattern": "^0x[a-fA-F0-9]{64}$"
              },
              "logIndex": {
                "type": "integer",
                "minimum": 0
              },
              "removed": {
                "type": "boolean"
              }
            }
          }
        },
        "status": {
          "type": "integer",
          "enum": [0, 1]
        },
        "logsBloom": {
          "type": "string",
          "pattern": "^0x[a-fA-F0-9]{512}$"
        }
      }
    },
    "blockHeader": {
      "type": "object",
      "required": [
        "parentHash",
        "sha3Uncles",
        "miner",
        "stateRoot",
        "transactionsRoot",
        "receiptsRoot",
        "logsBloom",
        "difficulty",
        "totalDifficulty",
        "number",
        "gasLimit",
        "gasUsed",
        "timestamp",
        "extraData",
        "mixHash",
        "nonce",
        "hash",
        "baseFeePerGas",
        "size"
      ],
      "properties": {
        "parentHash": {
          "type": "string",
          "pattern": "^0x[a-fA-F0-9]{64}$"
        },
        "sha3Uncles": {
          "type": "string",
          "pattern": "^0x[a-fA-F0-9]{64}$"
        },
        "miner": {
          "type": "string",
          "pattern": "^0x[a-fA-F0-9]{40}$"
        },
        "stateRoot": {
          "type": "string",
          "pattern": "^0x[a-fA-F0-9]{64}$"
        },
        "transactionsRoot": {
          "type": "string",
          "pattern": "^0x[a-fA-F0-9]{64}$"
        },
        "receiptsRoot": {
          "type": "string",
          "pattern": "^0x[a-fA-F0-9]{64}$"
        },
        "logsBloom": {
          "type": "string",
          "pattern": "^0x[a-fA-F0-9]{512}$"
        },
        "difficulty": {
          "type": "integer",
          "minimum": 0
        },
        "totalDifficulty": {
          "type": "integer",
          "minimum": 0
        },
        "number": {
          "type": "integer",
          "minimum": 0
        },
        "gasLimit": {
          "type": "integer",
          "minimum": 0
        },
        "gasUsed": {
          "type": "integer",
          "minimum": 0
        },
        "timestamp": {
          "type": "integer",
          "minimum": 0
        },
        "extraData": {
          "type": "string",
          "pattern": "^0x[a-fA-F0-9]*$"
        },
        "mixHash": {
          "type": "string",
          "pattern": "^0x[a-fA-F0-9]{64}$"
        },
        "nonce": {
          "type": "string",
          "pattern": "^0x[a-fA-F0-9]{16}$"
        },
        "hash": {
          "type": "string",
          "pattern": "^0x[a-fA-F0-9]{64}$"
        },
        "baseFeePerGas": {
          "type": "integer",
          "minimum": 0
        },
        "size": {
          "type": "integer",
          "minimum": 0
        }
      }
    },
    "receiptProof": {
      "type": "object",
      "required": ["proof", "value"],
      "properties": {
        "proof": {
          "type": "array",
          "items": {
            "type": "array",
            "items": {
              "type": "integer"
            }
          }
        },
        "value": {
          "type": "array",
          "items": {
            "type": "integer"
          }
        }
      }
    },
    "transactionProof": {
      "type": "object",
      "required": ["proof", "value"],
      "properties": {
        "proof": {
          "type": "array",
          "items": {
            "type": "array",
            "items": {
              "type": "integer"
            }
          }
        },
        "value": {
          "type": "array",
          "items": {
            "type": "integer"
          }
        }
      }
    }
  }
}

=== CNSLabs/agreements-data-standard/definition/templates/provable-inputs/transaction-proof.json
{
    "txHash": "0x8a5f12d36054e338c8ec49f1f79e4c0afe7f3ca3b1f253e10f1c936981bab69a",
    "proofDefinitionReference": "${erc20TransferProofDefinition}",
    
    "rawTx": {
      "hash": "0x8a5f12d36054e338c8ec49f1f79e4c0afe7f3ca3b1f253e10f1c936981bab69a",
      "nonce": 42,
      "from": "0x742d35Cc6634C0532925a3b844Bc454e4438f44e",
      "to": "0x6B175474E89094C44Da98b954EedeAC495271d0F",
      "value": "0",
      "gasPrice": "20000000000",
      "gas": "100000",
      "input": "0xa9059cbb000000000000000000000000a5407eae9ba41422680e2e00537571bcc53efbfd000000000000000000000000000000000000000000000000000000003b9aca00",
      "v": "0x25",
      "r": "0x1b5e176d927f8e9ab405058b2d2457392da3e20f328b16ddabcebc33eaac5fea",
      "s": "0x4ba69724e8f69de52f0125ad8b3c5c2cef33019bac3249e2c0a2192766d1721c",
      "chainId": 1
    },
    
    "txReceipt": {
      "transactionHash": "0x8a5f12d36054e338c8ec49f1f79e4c0afe7f3ca3b1f253e10f1c936981bab69a",
      "transactionIndex": 42,
      "type": 0,
      "blockHash": "0xf6b4b8c330d91e0ada6f40619f7f5e01c6d91a7d3bb67acb36578c0f0604ef08",
      "blockNumber": 16123450,
      "from": "0x742d35Cc6634C0532925a3b844Bc454e4438f44e",
      "to": "0x6B175474E89094C44Da98b954EedeAC495271d0F",
      "gasUsed": 65402,
      "cumulativeGasUsed": 7650402,
      "effectiveGasPrice": 20000000000,
      "contractAddress": null,
      "logs": [
        {
          "address": "0x6B175474E89094C44Da98b954EedeAC495271d0F",
          "topics": [
            "0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef",
            "0x000000000000000000000000742d35cc6634c0532925a3b844bc454e4438f44e",
            "0x000000000000000000000000a5407eae9ba41422680e2e00537571bcc53efbfd"
          ],
          "data": "0x000000000000000000000000000000000000000000000000000000003b9aca00",
          "blockNumber": 16123450,
          "transactionHash": "0x8a5f12d36054e338c8ec49f1f79e4c0afe7f3ca3b1f253e10f1c936981bab69a",
          "logIndex": 103,
          "removed": false
        }
      ],
      "status": 1,
      "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
    },
    
    "blockHeader": {
      "parentHash": "0x9b4f1b38a1085ed6f9d0c3a7835e8517b7e9f8d8f8fc9ab4e4702cc50c59ac5c",
      "sha3Uncles": "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
      "miner": "0xea674fdde714fd979de3edf0f56aa9716b898ec8",
      "stateRoot": "0x7af3d0a638ab8c8299a1c2c4c346edc8ce8a5e1f2fa4b6e1b61bac767f2d4f0b",
      "transactionsRoot": "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
      "receiptsRoot": "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
      "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
      "difficulty": 2,
      "totalDifficulty": 58750003716598352816469,
      "number": 16123450,
      "gasLimit": 30000000,
      "gasUsed": 7650402,
      "timestamp": 1672176065,
      "extraData": "0xd883010a11846765746888676f312e31392e32856c696e7578",
      "mixHash": "0x3d7e8678c2c523c20e27e2a024a277a3acaa7f5ba8d1c3b25800972fb41cc6db",
      "nonce": "0x0000000000000000",
      "hash": "0xf6b4b8c330d91e0ada6f40619f7f5e01c6d91a7d3bb67acb36578c0f0604ef08",
      "baseFeePerGas": 7,
      "size": 9768
    },
    
    "receiptProof": {
      "proof": [
        [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
        [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]
      ],
      "value": [31, 32, 33, 34, 35, 36, 37, 38, 39, 40]
    },
    
    "transactionProof": {
      "proof": [
        [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
        [51, 52, 53, 54, 55, 56, 57, 58, 59, 60],
        [61, 62, 63, 64, 65, 66, 67, 68, 69, 70]
      ],
      "value": [71, 72, 73, 74, 75, 76, 77, 78, 79, 80]
    }
  }
